# The main CI of Hibernate Search is http://ci.hibernate.org/job/hibernate-search/. Travis CI can be
# used in github forks. https://travis-ci.org/hibernate/hibernate-search is
# therefore deactivated. Activating Travis for your own fork is as easy as
# activating it in the travis site of your fork.

sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
install:
  # The Maven install provided by Travis is outdated, use Maven wrapper to get the latest version
  - mvn -N io.takari:maven:wrapper
  - ./mvnw -v
  # first run to download all the Maven dependencies without logging
  - ./mvnw -B -q clean install -DskipTests=true
  # we run checkstyle first to fail fast if there is a styling error
  - ./mvnw checkstyle:check
script:
  - ./mvnw -Pdocs,dist clean install
before_cache:
  # Do not put the artifacts we just built into the cache
  - rm -r $HOME/.m2/repository/org/hibernate/hibernate-search*
